---
title: "News"
---

# Upcoming

*   **11/2023**: Big Data Bowl workshop at the [2023 Carnegie Mellon Sports Analytics Conferece](http://stat.cmu.edu/cmsac/conference/2023/)

*   **09/2023**: Invited talk at the [2023 New England Symposium on Statistics in Sports](https://www.nessis.org) (NESSIS)

# Recent

*   **07/2023**: Paper *Here Comes the STRAIN: Analyzing Defensive Pass Rush in American Football with Player Tracking Data* was accepted for [publication in The American Statistician](https://www.tandfonline.com/doi/full/10.1080/00031305.2023.2242442)

*   **Summer 2023**: TA Advisor for [Carnegie Mellon Sports Analytics Camp 2023](https://www.stat.cmu.edu/cmsac/sure/2023/showcase/), part of the [Summer Undergraduate Research Experience (SURE) 2023](https://cmu-sure-2023.netlify.app/) program hosted by CMU Statistics & Data Science

*   **02/2023**: Named [finalist of the NFL Big Data Bowl 2023](https://operations.nfl.com/gameday/analytics/big-data-bowl/2023-big-data-bowl-finalists/) with entry [STRAIN: Sacks, Tackles, Rushing, Aggression INdex](https://www.kaggle.com/code/statsinthewild/strain-sacks-tackles-rushing-aggression-index)

*   **10/2022**: Awarded 3rd place of the Reproducible Research Competition (Open Methods Track) at the [2022 Carnegie Mellon Sports Analytics Conferece](http://stat.cmu.edu/cmsac/conference/2022/) (CMSAC) with my paper [Estimating Aging Curves: Using Multiple Imputation to Examine Career Trajectories of MLB Offensive Players](https://www.stat.cmu.edu/cmsac/conference/2022/assets/pdf/QuangNguyen.pdf)

*   **09/2022**: Invited talk at the [2022 Cascadia Symposium on Statistics in Sports](http://www.cascadiasports.com/) (CASSIS).

*   **08/2022**: Started my PhD in the [Department of Statistics and Data Science at Carnegie Mellon University](https://www.stat.cmu.edu/).

*   **05/2022**: Guest appearance on [Episode IX of the Open Source Sports Podcast](https://anchor.fm/open-source-sports/episodes/An-Examination-of-Sport-Climbing-with-Quang-Nguyen-e1injq9).

*   **03/2022**: Paper **An Examination of Olympic Sport Climbing Competition Format and Scoring System** was accepted for [publication in the Journal of Data Science](https://jds-online.org/journal/JDS/article/1273).

*   **Spring 2022**: Worked as an instructor in the [Department of Mathematics and Statistics](https://www.luc.edu/math) at [Loyola University Chicago](https://www.luc.edu).

*   **12/2021**: Completed my [MS in Applied Statistics](https://www.luc.edu/math/msappliedstat) at Loyola University Chicago.

*   **11/2021**: Awarded 1st place of the Reproducible Research Competition (Open Methods Track) at the [2021 Carnegie Mellon Sports Analytics Conferece](http://stat.cmu.edu/cmsac/conference/2021/) (CMSAC) with my paper [An Examination of Sport Climbing's Competition Format and Scoring System.](http://stat.cmu.edu/cmsac/conference/2021/assets/pdf/QuangNguyen.pdf)

*   **10/2021**: Won the Best Student Poster Award at the [2021 UConn Sports Analytics Conferece](https://statds.org/events/ucsas2021) (UCSAS) with my poster [Concerns Regarding Sport Climbing Competition Format and Scoring System: Who's Suffering?](https://statds.org/events/ucsas2021/posters/ucsas2021_08_Quang_Nguyen.pdf)

*   **10/2021**: Took part in the [2021 Humana-Mays Healthcare Analytics Case Competition](https://mays.tamu.edu/humana-tamu-analytics) (organized by Texas A&M University). Our team finished 2/50 in the [First Round Leaderboard](http://mays.tamu.edu/humana-tamu-analytics/wp-content/uploads/sites/113/2021/10/Round1_Results_FINAL-1.pdf), where the goal was to build a model for predicting vaccine hesitancy.

*   **09/2021**: Participated in a live coding session where I tried to predict the 2021 Brownlow Medal Winner for the Australian Football League (AFL). This was [Rob Nguyen](https://twitter.com/roberto_boberto)'s idea, where he wanted to pair up a stats person with no knowledge of Aussie rules with a journalist with domain expertise to see how well they can do at making predictions. Here are links to a [video recording](https://www.youtube.com/watch?v=Cd9yLYPSosM) and an [article](https://www.abc.net.au/news/2021-09-19/afl-trying-to-predict-the-2021-brownlow-medal-winner/100472246) on ABC News (Australia).

<!-- *   **07/2021**: I [ranked first in the Kaggle leaderboard](https://www.kaggle.com/c/sliced-s01e09-playoffs-1/leaderboard) of SLICED (a data science show) as an audience partipicant. The competition topic was [predicting baseball home runs](https://www.kaggle.com/c/sliced-s01e09-playoffs-1). -->
