---
title: "Research"
---

<!-- Below is a list of research and miscellaneous projects that I'm either currently working on or have completed. -->

## Publications

Ronald Yurko, **Quang Nguyen**, Konstantinos Pelechrinis.
"NFL Ghosts: A framework for evaluating defender positioning with conditional density estimation".
*Annals of Applied Statistics*, 2025+.
[[arXiv](https://arxiv.org/abs/2406.17220); [journal](https://www.e-publications.org/ims/submission/AOAS/user/submissionFile/70786?confirm=5d1c9ec1)]

**Quang Nguyen**, Ronald Yurko.
"A multilevel model with heterogeneous variances for snap timing in the National Football League".
*Journal of the Royal Statistical Society: Series A (Statistics in Society)*, 2025+.
[[arXiv](https://arxiv.org/abs/2502.16313); [journal](https://doi.org/10.1093/jrsssa/qnaf185)]
<br>
***(Semifinalist, NFL Big Data Bowl 2025)***

**Quang Nguyen**, Ruitong Jiang, Meg Ellingwood, Ronald Yurko.
"Fractional Tackles: Leveraging Player Tracking Data for Within-Play Tackling Evaluation in American Football".
*Scientific Reports (Nature Portfolio)*, 2025.
[[arXiv](https://arxiv.org/abs/2403.14769); [journal](https://doi.org/10.1038/s41598-025-85993-1)]
<br>
***(Finalist, NFL Big Data Bowl 2024)***

**Quang Nguyen**, Ronald Yurko, Gregory J. Matthews.
"Here Comes the STRAIN: Analyzing Defensive Pass Rush in American Football with Player Tracking Data".
*The American Statistician*, 2024.
[[arXiv](https://arxiv.org/abs/2305.10262); [journal](https://doi.org/10.1080/00031305.2023.2242442)]
<br>
***(Editors' Choice Collection)***
<br>
***(Finalist, NFL Big Data Bowl 2023)***

**Quang Nguyen**, Gregory J. Matthews.
"Filling the Gaps: A Multiple Imputation Approach to Estimating Aging Curves in Baseball".
*Journal of Sports Analytics*, 2024.
[[arXiv](https://arxiv.org/abs/2210.02383); [journal](https://doi.org/10.3233/JSA-240744)]
<br>
***(Finalist, Open Methodology Track, Reproducible Research Competition, Carnegie Mellon Sports Analytics Conference 2022)***

Benjamin S. Baumer, Gregory J. Matthews, **Quang Nguyen**.
"Big ideas in sports analytics and statistical tools for their investigation".
*Wiley Interdisciplinary Reviews: Computational Statistics*, 2023. 
[[arXiv](https://arxiv.org/abs/2301.04001); [journal](https://doi.org/10.1002/wics.1612)]

**Quang Nguyen**, Hannah Butler, Gregory J. Matthews.
"An Examination of Olympic Sport Climbing Competition Format and Scoring System".
*Journal of Data Science*, 2022. 
[[arXiv](https://arxiv.org/abs/2111.05310); [journal](https://doi.org/10.6339/22-JDS1042)]
<br>
***(Winner, Open Methodology Track, Reproducible Research Competition, Carnegie Mellon Sports Analytics Conference 2021)***
<br>
***(Winner, Student Poster Award, UConn Sports Analytics Symposium 2021)***

**Quang Nguyen**.
"Poisson Modeling and Predicting English Premier League Goal Scoring".
*New England Journal of Statistics in Data Science*, 2023.
[[arXiv](https://arxiv.org/abs/2105.09881); [journal](https://doi.org/10.51387/21-NEJSDS1)]
<br>
***(Co-Winner, Poster Competition, Undergrad/MS Group, New England Statistical Society NextGen: Data Science Day 2020)***

### Under Review

**Quang Nguyen**, Ronald Yurko.
"A Bayesian circular mixed-effects model for explaining variability in directional movement in American football".
*arXiv preprint arXiv:2507.06122*, 2025+.
[[arXiv](https://arxiv.org/abs/2507.06122)]

<!-- **Quang Nguyen**, Paolo Campana, Nynke M. D. Niezink. -->
<!-- "Co-evolution of cooperation and conflict among organized crime groups: Evidence from the United Kingdom". -->
<!-- 2025+. -->


### Other

**Quang Nguyen**, Ron Yurko.
"Down, set, hut! Explaining variability in snap timing on plays with motion". 
*NFL Big Data Bowl. Kaggle*, 2025.
[[link](https://www.kaggle.com/code/tindata/down-set-hut)]

**Quang Nguyen**, Larry Jiang, Meg Ellingwood, Ron Yurko.
"Momentum-based fractional tackles". 
*NFL Big Data Bowl. Kaggle*, 2024.
[[link](https://www.kaggle.com/code/tindata/momentum-based-fractional-tackles)]

Gregory J. Matthews, **Quang Nguyen**.
"STRAIN: Sacks, Tackles, Rushing, Aggression INdex". 
*NFL Big Data Bowl. Kaggle*, 2023.
[[link](https://www.kaggle.com/code/statsinthewild/strain-sacks-tackles-rushing-aggression-index)]

Benjamin S. Baumer, **Quang Nguyen**, Gregory J. Matthews.
"CRAN Task View: Sports Analytics".
*The Comprehensive R Archive Network*, 2022.
[[link](https://cran.r-project.org/web/views/SportsAnalytics.html)]


<!-- ### Current -->

<!-- |project|repo|pdf|slides| -->
<!-- |-|-|-|-| -->
<!-- |Estimating the Baseball Aging Curves Using Missing Data Methods| [`r fontawesome::fa("github")`](https://github.com/qntkhvn/agingcurve)||[`r fontawesome::fa("laptop")`](projects/aging.pdf)| -->
<!-- |An Examination of Sport Climbing Combined Format|[`r fontawesome::fa("github")`](https://github.com/qntkhvn/cmsac_rrc)|[`r fontawesome::fa("file-pdf")`](https://arxiv.org/pdf/2111.05310.pdf)|[`r fontawesome::fa("laptop")`](projects/climbing_cmsac_rrc.html)| -->

<!-- ### Past -->

<!-- |project|repo|pdf|html|slides|video| -->
<!-- |---------------------------|-|-|-|-|-| -->
<!-- |Poisson Modeling and Predicting English Premier League Goal Scoring (poster presented at UCSAS 2020)|[`r fontawesome::fa("github")`](https://github.com/qntkhvn/eplgoals)|[`r fontawesome::fa("file-pdf")`](https://arxiv.org/pdf/2105.09881.pdf)|[`r fontawesome::fa("file-code")`](https://bookdown.org/theqdata/honors_thesis)|[`r fontawesome::fa("laptop")`](https://statds.org/events/ucsas2020/posters/ucsas-1-Poster_UCSAS.pdf)|[`r fontawesome::fa("circle-play")`](https://www.dropbox.com/s/6xe2pntw25kzwpq/posterVideo.mp4?dl=0)| -->
<!-- |Analysis of Russell Westbrook's Triple-Doubles|[`r fontawesome::fa("github")`](https://github.com/qntkhvn/tripledouble)||[`r fontawesome::fa("file-code")`](https://bookdown.org/theqdata/data_science_capstone_project_report)|||| -->
<!-- |Analysis of CSV File Reading in `R`|[`r fontawesome::fa("github")`](https://github.com/qntkhvn/read_speed)|[`r fontawesome::fa("file-pdf")`](projects/csv_paper.pdf)||[`r fontawesome::fa("laptop")`](projects/csv_slides.pdf)|| -->
<!-- |Predicting Vaccine Hesitancy (2021 Humana-Mays Healthcare Analytics Case Competition)|[`r fontawesome::fa("github")`](https://github.com/qntkhvn/tamu_healthcare)|[`r fontawesome::fa("file-pdf")`](projects/humana.pdf)|||| -->
<!-- |Titanic - Machine Learning from Disaster (Kaggle Competition)|||[`r fontawesome::fa("file-code")`](projects/titanic.html)||| -->

<!-- |Predicting NFL Field Goal Outcomes||[`r fontawesome::fa("file-pdf")`](projects/nflfg.pdf)||[`r fontawesome::fa("laptop")`](projects/nflfg_pres.pdf)|[`r fontawesome::fa("circle-play")`](projects/nflfg.mp4)| -->

<!-- ## Miscellaneous -->

<!-- *   [Analysis of CSV File Reading in `R`](projects/csv_paper.pdf) -->

<!-- *   [Predicting Vaccine Hesitancy (2021 Humana-Mays Healthcare Analytics Case Competition)](projects/humana.pdf) -->

<!-- *   [SHAP and Shapley values](projects/shap.pdf) -->

<!-- *   [Sentiment analysis](projects/sentiment.html) -->

<!-- *   [Making a bingo board with `ggplot2`](projects/bingo.html) -->

<!-- *   [Wimbledon seeding heatmap](https://qntkhvn.github.io/wimbledon) (as of 2021) -->

<!-- *   [Data wrangling with `dplyr`/`tidyverse`](projects/tidy.html) -->

<!-- *   [Analysis of Russell Westbrook's Triple-Doubles](https://bookdown.org/theqdata/data_science_capstone_project_report) -->

<!-- *   [Essays on The Lady Tasting Tea](projects/ltt.pdf) -->

<!-- *   [Gauss and the parallel postulate](projects/gauss.pdf) -->

<!-- *   [Intro to Proofs portfolio and reflections](projects/proof.pdf) -->

<!-- *   [Me, myself, and Man United](projects/mu/mu.html) (written in 2018 - my first exposure to `bookdown`) -->

<!-- *   [Intro to Data Science portfolio](projects/dsportfolio/index.html) -->